spring:
  application:
    name: Cliente Service
  datasource:
    url: jdbc:mysql://localhost:3306/cliente_service_db?useSSL=false&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
server:
  port: 8090

logging:
  level:
    org.hibernate.orm.connections.pooling: OFF
